spring:
  config:
    import:
      - classpath:/application-dev.yml
      - classpath:/application-prod.yml
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:~/shop
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
