spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://{{ RDS address }}:3306/shop
    username: { { username } }
    password: { { password } }
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

api:
  open:
    naver:
      client-id: { { client-id } }
      client-secret: { { client-secret } }
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
